stages:
  - build
  - pre-test
  - package
  - post-test


build-app:
  image: node:18.17.1
  stage: build
  script:
    - npm install
    - npm start &
    - APP_PID=$!
    - sleep 10  
  after_script:
    - kill -2 $APP_PID 

# test-app:
#   image: python:latest
#   stage :  pre-test
#   script: 
#     - 



build_docker_image:
  stage: package
  image: docker:24.0.3
  services:
    - docker:24.0.3-dind
  script:
    - apk add --no-cache git
    - apk add --no-cache python3 py3-pip  
    - pip3 install awscli 
    - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 104081997798.dkr.ecr.us-east-1.amazonaws.com
    - docker build -t 104081997798.dkr.ecr.us-east-1.amazonaws.com/frontend-react:latest -f Dockerfile .
    - docker push 104081997798.dkr.ecr.us-east-1.amazonaws.com/frontend-react:latest
    - docker image ls
  only:
    - main

