version: "1"
services:
  development:
    build:
      context: .
      dockerfile: Dockerfile.development
    ports:
      - "3000:3000"
    volumes:
      - .:/home/app
      - /home/app/node_modules
