FROM node:18.17.1 AS frontend-builder
WORKDIR /app/frontend

COPY ./package.json ./package-lock.json ./
RUN npm install

FROM node:18.17.1 AS main-app
WORKDIR /home/app
COPY --from=frontend-builder /app/frontend/node_modules ./
COPY . ./

RUN npm cache clean -f
RUN npm install -g npm@10.1.0
RUN npm install -g react-scripts || \
    npm install -g react-scripts || \
    npm install -g react-scripts

RUN npm install react
RUN npm run build

EXPOSE 3000
CMD ["npm", "run","start"]
